baseURL = "https://teddyheinen.com"
languageCode = "en-us"
title = "Teddy Heinen"
theme = "personal"

[params]
    DateFormat = "2019 2 2"
    description = ""
    sidebarDescription = ""
    sidebarFreeText = "I'm a 21 year old Computer Science student at Texas A&M.  I enjoy reading Sci-Fi and Fantasy books and strategy games.  I program a lot in my free time and am currently interested in game console emulation.  I love writing scripts to automate anything I do repeatedly.  An interesting fact about me?  My favorite form of mathematical proof is the inductive proof.  "
	
	
[menu]
  [[menu.main]]
    identifier = "experience-menu"
    name = "Education & Work Experience"
    title = "experience"
  [[menu.main]]
    identifier = "skills-menu"
    name = "Skills"
    title = "skills"
  [[menu.main]]
    identifier = "interests-menu"
    name = "Interests"
    title = "interests"
  [[menu.main]]
    identifier = "service-menu"
    name = "Service"
    title = "service"
    