baseURL = "https://teddyheinen.com"
languageCode = "en-us"
title = "Teddy Heinen"
theme = "strange-case"

[params]
    colorScheme = "scheme-custom"
    DateFormat = "2019 2 2"
    description = ""
    sidebarDescription = ""
    sidebarFreeText = "I'm a 20 year old Computer Science student at Texas A&M.  I enjoy reading Sci-Fi and Fantasy books and strategy games.  I program a lot in my free time and am currently interested in game console emulation.  I love writing scripts to automate basically anything I do repeatedly.  "
	
	
[menu]
  [[menu.main]]
    identifier = "aboutme"
    name = "About Me"
    title = "aboutme"
    url = "/aboutme"
  [[menu.main]]
    identifier = "experience"
    name = "Education & Work Experience"
    title = "experience"
    url = "/experience"
  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    title = "skills"
    url = "/skills"